server:
  port: 8080

spring:
  application:
    name: dag-workflow-engine

logging:
  level:
    root: INFO
    com.gengzi.workflow: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
